import { useNavigate } from "react-router-dom";
import "./AccountPage.css"; // reuse the dark shell + top bar styles
import "./TosPage.css"; // reuse the readable prose column

// Public Privacy Policy page — no login required. Dark theme, yellow accents,
// mirrors TosPage's shell + prose styling.
function PrivacyPolicyPage() {
  const navigate = useNavigate();
  // Return where the user came from (e.g. the chat dropdown); fall back to home
  // for a fresh tab / direct visit so anonymous visitors aren't bounced to login.
  const goBack = () => {
    if (typeof window !== "undefined" && window.history.length > 1) navigate(-1);
    else navigate("/");
  };

  return (
    <div className="account-page">
      <header className="account-topbar">
        <button className="account-back" onClick={goBack} aria-label="Go back">
          ←
        </button>
        <a href="/" className="logo">
          <img src="/fetchit-logo.png" alt="FetchIt" className="logo-img" />
        </a>
        <span className="account-topbar-title">Privacy Policy</span>
      </header>

      <main className="account-main">
        <article className="tos-content">
          <h1>FetchIt Privacy Policy</h1>
          <p className="tos-dates">
            <strong>Effective Date:</strong> June 13, 2026
            <br />
            <strong>Last Updated:</strong> June 13, 2026
          </p>

          <p>
            This Privacy Policy explains how FetchIt collects, uses, stores,
            shares, and protects your personal information when you use the
            FetchIt platform, website, mobile application, or any related
            services. By using the Service, you agree to the collection and use
            of your information as described in this Privacy Policy.
          </p>

          <h2>1. Information We Collect</h2>

          <h3>1.1 Information You Provide Directly</h3>
          <ul>
            <li>
              Account information: name, email address, password or Google
              account details
            </li>
            <li>
              Shipping address: full name, address lines, city, state, ZIP,
              country
            </li>
            <li>
              Payment information: non-sensitive card metadata only (brand, last
              4 digits, expiry) — full card details handled exclusively by Stripe
            </li>
            <li>Display name chosen during onboarding</li>
            <li>Messages and requests sent through the Service</li>
          </ul>

          <h3>1.2 Information Generated by Your Use</h3>
          <ul>
            <li>
              Chat and conversation history — every message sent to the FetchIt
              AI assistant
            </li>
            <li>
              Order history — product name, retailer, price, service fee, status,
              category
            </li>
            <li>Usage data — token usage per session and weekly totals</li>
            <li>Shopping preferences inferred from searches and purchases</li>
            <li>
              Device and technical information — browser type, IP address, OS,
              access times
            </li>
          </ul>

          <h3>1.3 Information from Third Parties</h3>
          <ul>
            <li>Google — name, email, profile picture if you sign in with Google</li>
            <li>Stripe — payment confirmation and non-sensitive card metadata</li>
            <li>
              Zinc Technologies — order confirmation, tracking, and return status
            </li>
          </ul>

          <h2>2. How We Use Your Information</h2>
          <ul>
            <li>
              To provide the Service — processing searches, placing orders,
              managing your account
            </li>
            <li>
              To communicate with you — order confirmations, shipping updates,
              security emails
            </li>
            <li>
              To process payments — charging your saved payment method via Stripe
            </li>
            <li>To enforce usage limits — tracking token consumption per plan</li>
            <li>
              To improve the Service — analyzing usage patterns to improve
              features
            </li>
            <li>To comply with legal obligations</li>
          </ul>

          <h2>3. AI Training and Data Sharing with xAI</h2>
          <p>
            <strong>This section requires your careful attention.</strong>
          </p>
          <p>
            FetchIt will use Grok 4.3, developed and operated by xAI, Inc., to power
            its shopping assistant.
          </p>
          <p>By using FetchIt, you acknowledge and agree that:</p>
          <ul>
            <li>
              Your conversations with the FetchIt AI assistant — including search
              queries, product requests, shopping preferences, purchase history,
              and all chat interactions — may be transmitted to xAI and used by
              xAI and its affiliates to train, improve, fine-tune, and develop
              their artificial intelligence models.
            </li>
            <li>
              This data sharing will occur as a condition of FetchIt&apos;s use of
              xAI&apos;s API services.
            </li>
            <li>
              You cannot opt out of this data sharing while using the Service. If
              you do not consent to your conversation data being used to train AI
              models, you must not use the Service.
            </li>
            <li>
              FetchIt does not control how xAI uses your data beyond what is
              described in xAI&apos;s own Privacy Policy at x.ai/privacy.
            </li>
            <li>
              Data shared with xAI may include personal details mentioned in
              conversation, such as gift recipient names and personal preferences.
            </li>
          </ul>
          <p>
            We strongly recommend you do not share sensitive personal information
            (Social Security numbers, full financial account numbers, medical
            information) in the FetchIt chat interface.
          </p>

          <h2>4. How We Share Your Information</h2>
          <p>
            We do not sell your personal information to advertisers or
            third-party data brokers. We share information only with:
          </p>
          <ul>
            <li>Supabase — database hosting and authentication</li>
            <li>Stripe — payment processing and subscription management</li>
            <li>Zinc Technologies — order placement, tracking, and returns</li>
            <li>xAI — AI inference and model training as described in Section 3</li>
            <li>Resend — transactional email delivery</li>
            <li>
              Retailers — your shipping address and order details will be shared with
              applicable retailers (Amazon, Walmart, etc.) through Zinc to fulfill
              your orders
            </li>
            <li>
              Legal authorities — if required by law or to protect rights and
              safety
            </li>
            <li>Business transfers — if FetchIt is acquired or merged</li>
          </ul>

          <h2>5. Data Retention</h2>
          <ul>
            <li>Account data: retained until you delete your account</li>
            <li>
              Order history: retained for 7 years for tax and legal compliance
            </li>
            <li>
              Chat history: retained until you delete chats or your account
            </li>
            <li>Usage data: retained for 13 months</li>
            <li>
              On account deletion, personal data is deleted within 30 days except
              where required by law
            </li>
          </ul>

          <h2>6. Data Security</h2>
          <ul>
            <li>All data transmitted over encrypted HTTPS</li>
            <li>
              Payment card details never stored on our servers — handled by Stripe
              (PCI DSS compliant)
            </li>
            <li>Shipping addresses stored in Supabase with Row Level Security</li>
            <li>
              Sensitive pages require password or Google reauthentication
            </li>
            <li>
              No method of transmission is 100% secure — we cannot guarantee
              absolute security
            </li>
          </ul>

          <h2>7. Your Rights and Choices</h2>
          <ul>
            <li>
              Access: view your account info, orders, and analytics within the
              Service
            </li>
            <li>
              Correction: update name, address, and payment method in account
              settings
            </li>
            <li>
              Deletion: delete your account anytime through account settings
            </li>
            <li>Marketing emails: unsubscribe via link in any marketing email</li>
            <li>
              AI training: you will not be able to opt out of xAI training while using the
              Service
            </li>
          </ul>

          <h2>8. Cookies and Tracking</h2>
          <p>
            FetchIt uses localStorage and sessionStorage for session preferences
            and UI state. We do not use advertising cookies or third-party
            tracking pixels.
          </p>

          <h2>9. Children&apos;s Privacy</h2>
          <p>
            The Service is not directed at children under 18. We do not knowingly
            collect information from anyone under 18. Contact support@fetchit.com
            if you believe we have collected information from a minor.
          </p>

          <h2>10. International Users</h2>
          <p>
            FetchIt is operated from the United States and is currently available
            to US users only. Your information will be stored and processed in the
            United States.
          </p>

          <h2>11. Third-Party Links</h2>
          <p>
            This Privacy Policy does not apply to third-party websites linked from
            the Service. Review the privacy policies of any third-party sites you
            visit.
          </p>

          <h2>12. Changes to This Privacy Policy</h2>
          <p>
            We will notify you of material changes by updating the Last Updated
            date and sending email notification where appropriate. Continued use
            constitutes acceptance.
          </p>

          <h2>13. Contact Us</h2>
          <p>FetchIt — Email: support@fetchit.com</p>

          <p className="tos-closing">
            By using FetchIt, you acknowledge that you have read this Privacy
            Policy and understand how your information is collected, used, and
            shared.
          </p>
        </article>
      </main>
    </div>
  );
}

export default PrivacyPolicyPage;
